apiVersion: v1
kind: Service
metadata:
  name: {{ include "beautyrec.fullname" . }}-backend
  labels:
    {{- include "beautyrec.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    {{- include "beautyrec.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
