apiVersion: v1
kind: Service
metadata:
  name: {{ include "beautyrec.fullname" . }}-frontend
  labels:
    {{- include "beautyrec.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    {{- include "beautyrec.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
