apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "beautyrec.fullname" . }}-backend
  labels:
    {{- include "beautyrec.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "beautyrec.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "beautyrec.fullname" . }}-frontend
  labels:
    {{- include "beautyrec.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "beautyrec.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
